name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches: ["master"]
    tags: ["v*"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: michaelmass/actions/dagger@master
        with:
          source: ci/deploy.ts
          infisical-token: ${{ secrets.INFISICAL_TOKEN }}
          infisical-workspace-id: ${{ secrets.INFISICAL_WORKSPACE_ID }}
          infisical-environment: production
